version: "3.2"

services:
  php:
    container_name: front
    build: ./front-docker-files
    ports:
      - 80:80
    volumes:
      - ./front/piloto:/var/www/html/

  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --max_allowed_packet=1073741824 --sql_mode=""
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwordRoot
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_TCP_PORT: 3306
    
