# Use a imagem oficial do PHP com FPM
FROM php:7.4-fpm

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /var/www/html

# Copie o código PHP para o contêiner
COPY . /var/www/html

# Instale dependências
RUN apt-get update && \
    apt-get install -y \
        libzip-dev \
        zip \
        p7zip-full \
        unzip \
        git \
        curl 

# Instale Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Instale extensões PHP
RUN docker-php-ext-install pdo pdo_mysql

# Criação dos diretórios e definição de permissões
RUN mkdir -p storage/framework/sessions storage/framework/views storage/framework/cache storage/logs bootstrap/cache && \
    chown -R www-data:www-data storage bootstrap/cache && \
    chmod -R 775 storage bootstrap/cache